# Generated by Django 4.0.4 on 2022-05-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gasolinera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CP', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=50)),
                ('latitude', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=20)),
                ('margen', models.CharField(max_length=5)),
                ('municipality', models.CharField(max_length=50)),
                ('biodiesel', models.CharField(max_length=8)),
                ('bioetanol', models.CharField(max_length=8)),
                ('GNC', models.CharField(max_length=8)),
                ('GNL', models.CharField(max_length=8)),
                ('GLP', models.CharField(max_length=8)),
                ('diesel_A', models.CharField(max_length=8)),
                ('diesel_B', models.CharField(max_length=8)),
                ('diesel_premium', models.CharField(max_length=8)),
                ('gasoline_95_E10', models.CharField(max_length=8)),
                ('gasoline_95_E5', models.CharField(max_length=8)),
                ('gasoline_95_E5_premium', models.CharField(max_length=8)),
                ('gasoline_98_E10', models.CharField(max_length=8)),
                ('gasoline_98_E5', models.CharField(max_length=8)),
                ('hydrogen', models.CharField(max_length=8)),
                ('province', models.CharField(max_length=20)),
                ('remission', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('sell_type', models.CharField(max_length=8)),
                ('bioetanol_perc', models.CharField(max_length=8)),
                ('ester_met_perc', models.CharField(max_length=8)),
                ('IDEESS', models.CharField(max_length=8)),
                ('ID_municipality', models.CharField(max_length=8)),
                ('ID_province', models.CharField(max_length=8)),
                ('ID_CCAA', models.CharField(max_length=8)),
            ],
        ),
    ]
