# Generated by Django 4.0.4 on 2022-05-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinapp', '0002_alter_gasolinera_location_alter_gasolinera_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasolinera',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
