# Generated by Django 4.0.4 on 2022-05-18 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinapp', '0003_alter_gasolinera_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasolinera',
            name='municipality',
            field=models.CharField(max_length=100),
        ),
    ]
