# Generated by Django 4.0.4 on 2022-05-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinapp', '0004_alter_gasolinera_municipality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasolinera',
            name='latitude',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='gasolinera',
            name='longitude',
            field=models.CharField(max_length=30),
        ),
    ]
