# Generated by Django 4.0.4 on 2022-05-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinapp', '0005_alter_gasolinera_latitude_alter_gasolinera_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasolinera',
            name='province',
            field=models.CharField(max_length=30),
        ),
    ]
