# Generated by Django 4.0.4 on 2022-05-18 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinapp', '0006_alter_gasolinera_province'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=40)),
                ('validas', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('invalidas', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
            ],
        ),
    ]
