# Generated by Django 4.0.4 on 2022-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinapp', '0007_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasolinera',
            name='id',
        ),
        migrations.AlterField(
            model_name='gasolinera',
            name='IDEESS',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
