# Generated by Django 4.0.4 on 2022-05-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasolinapp', '0008_remove_gasolinera_id_alter_gasolinera_ideess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gasolinera',
            name='margen',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='gasolinera',
            name='sell_type',
            field=models.CharField(max_length=30),
        ),
    ]
